/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoComGradle;

public class App {
	public Double getGreeting() {
        double soma = 0.0;
        int n = 10;
        for (int i = 0; i < n; i++) {
			soma += i;
		}
        return soma;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
